Repository GDSC-Hongik/rental-system-mango-server, pull requests merged in 2024-08, with the labels that each got.

#19 feat: 카테고리 조회 기능 구현
  src/main/java/mango/rentalsystem/domain/category/api/CategoryController.java
  src/main/java/mango/rentalsystem/domain/category/application/CategoryService.java
  src/main/java/mango/rentalsystem/domain/category/dao/CategoryRepository.java
  src/main/java/mango/rentalsystem/domain/category/domain/Category.java
  src/main/java/mango/rentalsystem/domain/category/dto/request/CategoryRequest.java
  src/main/java/mango/rentalsystem/domain/category/dto/response/CategoryResponse.java
Labels: ⭐️ feature

#25 fix: application.yml 파일 redis 오타 수정
  src/main/resources/application.yml
Labels: 🐛 bug

#22 feat: 카테고리 추가 api 구현
  build.gradle
  src/main/java/mango/rentalsystem/domain/category/api/CategoryController.java
  src/main/java/mango/rentalsystem/domain/category/application/CategoryService.java
  src/main/java/mango/rentalsystem/domain/category/dao/CategoryRepository.java
  src/main/java/mango/rentalsystem/domain/category/domain/Category.java
  src/main/java/mango/rentalsystem/domain/category/dto/request/CategoryCreateRequest.java
  src/main/java/mango/rentalsystem/domain/department/dao/DepartmentRepository.java
  src/main/java/mango/rentalsystem/global/exception/CustomException.java
  src/main/java/mango/rentalsystem/global/exception/ErrorCode.java
  src/main/java/mango/rentalsystem/global/exception/ErrorResponse.java
  src/main/java/mango/rentalsystem/global/exception/GlobalExceptionHandler.java
Labels: ⭐️ feature

#26 feat: Department 도메인 구현
  src/main/java/mango/rentalsystem/domain/department/api/DepartmentController.java
  src/main/java/mango/rentalsystem/domain/department/application/DepartmentService.java
  src/main/java/mango/rentalsystem/domain/department/dao/DepartmentRepository.java
  src/main/java/mango/rentalsystem/domain/department/domain/DailyRentalTime.java
  src/main/java/mango/rentalsystem/domain/department/domain/Department.java
  src/main/java/mango/rentalsystem/domain/department/dto/request/DepartmentInfoUpdateRequest.java
  src/main/java/mango/rentalsystem/domain/department/dto/request/DepartmentRentalTimeUpdateRequest.java
  src/main/java/mango/rentalsystem/domain/department/dto/response/DepartmentResponse.java
  src/main/java/mango/rentalsystem/domain/rental/api/RentalController.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
  src/main/java/mango/rentalsystem/domain/rental/dao/RentalRepository.java
  src/main/java/mango/rentalsystem/domain/rental/dto/request/RentalRequest.java
Labels: ⭐️ feature

#29 feat: Rental 도메인 구현
  src/main/java/mango/rentalsystem/domain/rental/api/RentalController.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
  src/main/java/mango/rentalsystem/domain/rental/dao/RentalRepository.java
  src/main/java/mango/rentalsystem/domain/rental/domain/Rental.java
  src/main/java/mango/rentalsystem/domain/rental/domain/RentalStatus.java
  src/main/java/mango/rentalsystem/domain/rental/dto/request/RentalCreateRequest.java
  src/main/java/mango/rentalsystem/domain/rental/dto/request/RentalReviewRequest.java
  src/main/java/mango/rentalsystem/domain/rental/dto/request/RentalStatusUpdateRequest.java
  src/main/java/mango/rentalsystem/domain/rental/dto/response/RentalCreateResponse.java
  src/main/java/mango/rentalsystem/domain/rental/dto/response/RentalFindResponse.java
  src/main/java/mango/rentalsystem/domain/rental/validator/RentalStatusSubset.java
  src/main/java/mango/rentalsystem/domain/rental/validator/RentalStatusSubsetValidator.java
  src/main/java/mango/rentalsystem/global/config/SchedulingConfig.java
Labels: ⭐️ feature

#33 feat: member 도메인 구현
  src/main/java/mango/rentalsystem/domain/member/api/MemberController.java
  src/main/java/mango/rentalsystem/domain/member/application/MemberService.java
  src/main/java/mango/rentalsystem/domain/member/domain/Member.java
  src/main/java/mango/rentalsystem/domain/member/dto/UpdateMemberRequest.java
  src/main/java/mango/rentalsystem/domain/member/dto/UpdateMemberRequestByAdmin.java
Labels: ⭐️ feature

#34 feat: GlobalExceptionHandler 적용
  src/main/java/mango/rentalsystem/domain/auth/application/AuthService.java
  src/main/java/mango/rentalsystem/domain/department/application/DepartmentService.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
  src/main/java/mango/rentalsystem/domain/rental/validator/RentalStatusSubsetValidator.java
  src/main/java/mango/rentalsystem/global/config/WebSecurityConfig.java
  src/main/java/mango/rentalsystem/global/exception/ErrorCode.java
  src/main/java/mango/rentalsystem/global/exception/ErrorResponse.java
  src/main/java/mango/rentalsystem/global/exception/GlobalExceptionHandler.java
  src/main/java/mango/rentalsystem/global/security/JwtAuthenticationFilter.java
  src/main/java/mango/rentalsystem/global/security/JwtExceptionFilter.java
  src/main/java/mango/rentalsystem/global/security/JwtTokenProvider.java
Labels: ⭐️ feature

#42 feat: RentalService에 itemStatus 수정 로직 구현
  src/main/java/mango/rentalsystem/domain/item/application/ItemService.java
  src/main/java/mango/rentalsystem/domain/item/domain/Item.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
  src/main/java/mango/rentalsystem/domain/rental/domain/Rental.java
  src/main/java/mango/rentalsystem/global/exception/ErrorCode.java
Labels: ⭐️ feature

#43 refactor: Department 엔티티에서 운영시간 검증하도록 개선
  src/main/java/mango/rentalsystem/domain/department/domain/Department.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
Labels: ♻️ refactor

#44 fix: 물품 생성 API에서 물품 상태 및 물품 리뷰 입력 제한
  src/main/java/mango/rentalsystem/domain/item/application/ItemService.java
  src/main/java/mango/rentalsystem/domain/item/domain/Item.java
  src/main/java/mango/rentalsystem/domain/item/dto/request/ItemCreateRequest.java
Labels: 🐛 bug

#45 feat: RentalService에 rentalBannedDate 수정 로직 구현
  src/main/java/mango/rentalsystem/domain/member/domain/Member.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
  src/main/java/mango/rentalsystem/domain/rental/domain/Rental.java
  src/main/java/mango/rentalsystem/global/exception/ErrorCode.java
Labels: ⭐️ feature

#46 refactor: Member 도메인 리팩토링
  src/main/java/mango/rentalsystem/domain/member/api/MemberController.java
  src/main/java/mango/rentalsystem/domain/member/application/MemberService.java
  src/main/java/mango/rentalsystem/domain/member/dao/MemberRepository.java
  src/main/java/mango/rentalsystem/domain/member/domain/Member.java
  src/main/java/mango/rentalsystem/domain/member/dto/UpdateMemberRequest.java
  src/main/java/mango/rentalsystem/domain/member/dto/UpdateMemberRequestByAdmin.java
  src/main/java/mango/rentalsystem/domain/member/dto/request/MemberCreateRequest.java
  src/main/java/mango/rentalsystem/domain/member/dto/request/MemberInfoUpdateRequest.java
  src/main/java/mango/rentalsystem/domain/member/dto/request/MemberPasswordUpdateRequest.java
  src/main/java/mango/rentalsystem/domain/member/dto/response/MemberCreateResponse.java
  src/main/java/mango/rentalsystem/domain/member/dto/response/MemberFindResponse.java
  src/main/java/mango/rentalsystem/domain/member/utils/CsvUtil.java
  src/main/java/mango/rentalsystem/global/exception/ErrorCode.java
Labels: ♻️ refactor

#48 fix: 대여 정지 기간 검증 로직에서 null 검증하도록 수정
  src/main/java/mango/rentalsystem/domain/member/domain/Member.java
Labels: 🐛 bug

#55 feat: 대여 조회 로직에 rentalStatus에 따른 분류 로직 추가
  src/main/java/mango/rentalsystem/domain/rental/api/RentalController.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
  src/main/java/mango/rentalsystem/domain/rental/dao/RentalRepository.java
  src/main/java/mango/rentalsystem/domain/rental/dto/request/RentalFindRequest.java
  src/main/java/mango/rentalsystem/domain/rental/dto/request/RentalRequest.java
Labels: ⭐️ feature

#56 refactor: pathVariable에서 memberId 제거
  src/main/java/mango/rentalsystem/domain/department/api/DepartmentController.java
  src/main/java/mango/rentalsystem/domain/department/application/DepartmentService.java
  src/main/java/mango/rentalsystem/domain/member/api/MemberController.java
  src/main/java/mango/rentalsystem/domain/member/application/MemberService.java
  src/main/java/mango/rentalsystem/domain/rental/api/RentalController.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
Labels: ♻️ refactor

#59 chore: 배포 전 코드 수정
  src/main/java/mango/rentalsystem/domain/category/api/CategoryController.java
  src/main/java/mango/rentalsystem/domain/category/application/CategoryService.java
  src/main/java/mango/rentalsystem/domain/category/dao/CategoryRepository.java
  src/main/java/mango/rentalsystem/domain/category/domain/Category.java
  src/main/java/mango/rentalsystem/domain/category/dto/response/CategoryDetailResponse.java
  src/main/java/mango/rentalsystem/domain/category/dto/response/CategorySummaryResponse.java
  src/main/java/mango/rentalsystem/domain/department/domain/Department.java
  src/main/java/mango/rentalsystem/domain/item/api/ItemController.java
  src/main/java/mango/rentalsystem/domain/item/application/ItemService.java
  src/main/java/mango/rentalsystem/domain/item/dao/ItemRepository.java
  src/main/java/mango/rentalsystem/domain/item/domain/Item.java
  src/main/java/mango/rentalsystem/domain/item/dto/request/ItemModifyRequest.java
  src/main/java/mango/rentalsystem/domain/item/dto/response/ItemDetailResponse.java
  src/main/java/mango/rentalsystem/domain/member/domain/Member.java
  src/main/java/mango/rentalsystem/domain/member/dto/response/MemberCreateResponse.java
  src/main/java/mango/rentalsystem/domain/member/dto/response/MemberFindResponse.java
  src/main/java/mango/rentalsystem/domain/member/utils/CsvUtil.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
  src/main/java/mango/rentalsystem/domain/rental/dao/RentalRepository.java
  src/main/java/mango/rentalsystem/domain/rental/domain/Rental.java
  src/main/java/mango/rentalsystem/domain/rental/dto/response/RentalCreateResponse.java
  src/main/java/mango/rentalsystem/domain/rental/dto/response/RentalFindResponse.java
  src/main/java/mango/rentalsystem/domain/rental/validator/RentalStatusSubset.java
  src/main/java/mango/rentalsystem/domain/rental/validator/RentalStatusSubsetValidator.java
  src/main/java/mango/rentalsystem/global/InitDb.java
  src/main/java/mango/rentalsystem/global/exception/CustomException.java
  src/main/java/mango/rentalsystem/global/exception/ErrorResponse.java
  src/main/resources/application.yml
Labels: ⚙️ chore

#61 fix: 배포 버그 수정
  src/main/java/mango/rentalsystem/domain/category/domain/Category.java
  src/main/java/mango/rentalsystem/domain/member/dto/response/MemberCreateResponse.java
  src/main/java/mango/rentalsystem/domain/rental/application/RentalService.java
  src/main/java/mango/rentalsystem/global/InitDb.java
  src/main/java/mango/rentalsystem/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: 🐛 bug

#63 chore: docker 세팅
  Dockerfile
  docker-compose.yml
Labels: ⚙️ chore

#65 fix: AuthService의 로그인 메서드에서 refresh token 삭제하도록 수정
  src/main/java/mango/rentalsystem/domain/auth/application/AuthService.java
Labels: 🐛 bug
